### ISSUE TITLE
the skin is to big for my task bar.

### ISSUE THREAD

**Issue by CemJann** [Meti0X7CB/WinTaskical#1]
the skin is to big for my task bar.
![Screenshot 2024-02-21 210518](https://github.com/Meti0X7CB/WinTaskical/assets/160784166/370bd087-f8ae-4ce3-8580-78b8a32dc0c1)

**Comment by Meti0X7CB** [comment]
Make sure scaling is off for Rainmeter application. To do this you can right click the application where its installed and click on "Change High DPI settings"
<img width="304" alt="image" src="https://github.com/Meti0X7CB/WinTaskical/assets/8690114/9cf23999-9d0b-4336-95f7-c6ecfcbc8f72">
Turn on the "Override high DPI scaling behavior" 
![image](https://github.com/Meti0X7CB/WinTaskical/assets/8690114/09260da5-4108-42f6-8a7a-a1af0cdd8e03)
 
Restart rainmeter for it to take effect.
If this didn't align the taskbar correctly, make sure your windows scaling is the same as "Scale" in the skin. For example if you have 150% in windows, you should set "Scale" value in the skin to 1.5.
Reload the skin for this to take effect.
