### ISSUE TITLE
Skin covers taskbar when just on desktop

### ISSUE THREAD

**Issue by Kieran-C** [Meti0X7CB/WinTaskical#2]
When I go to the desktop (minimise all windows) the skin then covers the taskbar so I can't click anything on it. Is there a workaround for this, or have I simply set something up incorrectly? I understand that when it comes to taskbar priority, Windows has total control so rainmeter cant control when the taskbar gets hidden, but is there a way of working around this?

Another smaller issue, is there a way to change what audio output device the audio meter listens to, rather than just go with system default?

**Comment by Meti0X7CB** [comment]
In rainmeter setting if the position of skin is set to _Normal_ or _Bottom_ or _On Desktop_, the skin should stay behind windows taskbar.

![image](https://github.com/Meti0X7CB/WinTaskical/assets/8690114/0a523c9c-1f36-49dc-ba12-401dfe4fbaa7)

What do you have this set to?

**Comment by Kieran-C** [comment]
I have tried Normal, Bottom and On desktop, all behave the same for me

<img width="382" alt="image" src="https://github.com/Meti0X7CB/WinTaskical/assets/48714752/64cf2466-78a7-4ed3-ac95-a9d3602f4cbb">

It works complelty fine when there is a window open somewhere on the screen, but as soon as it is just the desktop, the taskbar icons all become covered.

What confuses me further is as I have 3 screens, I have duplicated just the frosted bar part you have made to frost the background of the taskbar on the other screens, and they all behave normally even on desktop, it is just the one on the primary display with the player that is doing this. I have unloaded these too to make sure that its not causing conflicts and even with just the primary display loaded, the desktop issue is still there

**Comment by Meti0X7CB** [comment]
That's very strange as I can't reproduce this it's hard for me to find what's causing it.
A few things to confirm, are you using any windows taskbar modification (Start 11 and etc)?
Does this only happen on primary display?

**Comment by Kieran-C** [comment]
Only running Rainmeter and TranslucentTB, no other modification software.
It only happens on my primary display, just moved it to secondary and the issue doesn't happen. I can try deleting it and adding the skin in fresh again to see if that fixes it, but the only setting I changed was the scaling option

**Comment by foursplaysroblox** [comment]
I also have the same issue

**Comment by Meti0X7CB** [comment]
Do you happen to have live wallpaper? wallpaper engine for example

**Comment by foursplaysroblox** [comment]
no

**Comment by foursplaysroblox** [comment]
is there a fix for it?

**Comment by Meti0X7CB** [comment]
This was tested by a community member on discord and it seems to be a Win 10 issue. 
I can't produce the bug on Win 11 fresh install with Rainmeter and TranslucentTB.

**Comment by foursplaysroblox** [comment]
> This was tested by a community member on discord and it seems to be a Win 10 issue. I can't produce the bug on Win 11 fresh install with Rainmeter and TranslucentTB.

strange it happens to me on win 11 for some reason
