### ISSUE TITLE
Right sided widgets for non centered taskbars

### ISSUE THREAD

**Issue by lopya76** [Meti0X7CB/WinTaskical#5]
![image](https://github.com/user-attachments/assets/4c42d64d-0745-44c5-aad3-ae42f8cf8c9f)

**Comment by Meti0X7CB** [comment]
Next release I will add right side panels for those that dont have centered taskbar or just prefer it to be on the right side.
However in your case, you can use the style with weather in your case which would shift to the right a bit.

**Comment by Meti0X7CB** [comment]
Added in 2.0 release!
